[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'shanghai'
via_ir = false
gas_limit = 10000000000
ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'read-write', path = './script/config/' },
]